name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    strategy:
      fail-fast: false
      matrix:
        engine: [ 'pdfLaTeX', 'LuaLaTeX', 'XeLaTeX' ]

    name: Engine ${{ matrix.engine }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ClassicThesis.tex
          latexmk_use_xelatex: ${{ matrix.engine == 'XeLaTeX' }}
          latexmk_use_lualatex: ${{ matrix.engine == 'LuaLaTeX' }}
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF ${{ matrix.engine }}
          path: ClassicThesis.pdf